version: "3"

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  celery:
    build: .
    container_name: celery-worker
    command: celery -A youtube_search worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A youtube_search beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
volumes:
  database_data:
